const habits = [
  {
    id: 1,
    habit_name: 'Exercise',
    habit_subtext: 'Workout for 30 minutes',
    repeat_days: ['Monday', 'Wednesday', 'Friday'],
    repeat_times: '3',
    repeat_option: 'ticked days',
    habit_created_date: '2023-04-15',
    completed_dates: {
      '2023-04-17': true,
      '2023-04-19': true,
    },
    expected_dates: {},
  },
  {
    id: 2,
    habit_name: 'Meditate',
    habit_subtext: 'Meditate for 10 minutes',
    repeat_days: ['Tuesday', 'Thursday', 'Saturday'],
    repeat_times: '3',
    repeat_option: 'ticked days',
    habit_created_date: '2023-04-15',
    completed_dates: {
      '2023-04-18': true,
      '2023-04-20': false,
    },
    expected_dates: {},
  },
  {
    id: 3,
    habit_name: 'Read',
    habit_subtext: 'Read 20 pages',
    repeat_days: [],
    repeat_times: '2',
    repeat_option: 'weekly',
    habit_created_date: '2023-04-15',
    completed_dates: {
      '2023-04-17': true,
      '2023-04-19': false,
    },
    expected_dates: {},
  },
  {
    id: 4,
    habit_name: 'Journal',
    habit_subtext: 'Write about your day',
    repeat_days: [],
    repeat_times: '4',
    repeat_option: 'weekly',
    habit_created_date: '2023-04-15',
    completed_dates: {
      '2023-04-17': true,
      '2023-04-18': true,
      '2023-04-19': true,
    },
    expected_dates: {},
  },
];